runtime: nodejs18

instance_class: F2
env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "efkhlqawuuerlkbcinhwyzrdclsnyopdlulwlswyamyjjlnvtnwbbglszpduilrxtcozwjhetcudhrmsfdkndcijuadatlowyyelmfhaqslbzsgmeysjvasznzta"
JWT_EXPIRES: "14d"
AWS_STORAGE_BUCKET: "himti"
AWS_STORAGE_ENDPOINT: "https://vivfqijtjlovgptrwica.supabase.co/storage/v1"
AWS_STORAGE_REGION: "ap-southeast-1"
AWS_STORAGE_ACCESS_KEY: "2404e5f08497609a863ff9cf5b30a7a2"
AWS_STORAGE_SECRET_KEY: "b65b57c53ebd49bee171bb8ce81a58e7d841537930378fda0b189a99c2272420"
DATABASE_URL: "postgresql://himti_db_owner:N2OLvE6cxJhs@ep-lucky-waterfall-a1ry1meu.ap-southeast-1.aws.neon.tech/himti_db?sslmode=require"
ANGGOTA_CODE: "HIMTI091011"
SMTP_USER: "aseloleasese@gmail.com"
SMTP_PASSWORD: "FScBrpOVdDU5W1qJ"
SMTP_HOST: "smtp-relay.brevo.com"
SMTP_PORT: 587
SMTP_LOGIN: "62e921001@smtp-brevo.com"
EMAIL_SENDER: "himti.umt11@gmail.com"
FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-c4xoy@flutter-himti-app-b2d87.iam.gserviceaccount.com"
FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+VxZ5y6bHblm5\niMTWpfFAR9SqHS6966V21uqCU/7ZvMgpmnm6U6FbI4YDG/DQuq0Nc7GNgjVC9kjg\nWUYIjWb61O3XmOxZylen/d+pL4IR8GTHseUdBUuZP2oBwYt7Cx0PqIApwdUmY4sA\nStliKURUSH1PkkfEwoeLlfUbtOEOoWcma4gSBXpRkAhfE5C6thq/I5VTyi/0+OMw\nrCzL8VAiKRgr7BUgybcA+tL0+4tG9mvJo2qfSDoaiBpZy327r3h8Xt9I2VEQTKg6\nD73fHyFu9sROGy+xV1bjgtO8tzWuVrSIX9hFigTXN9aZuWP+L5sTA28cZ+HDnPIO\nKS0lqq+NAgMBAAECggEAF246BpEyvR8Q7X1wGapAyfRtsek4vUlaS4hGQvfbCeuq\nyjBJZs3vsXvsfcp9OPyZ2+uPgkdyjgUqUG+85sWdVShMBPu+sIjvhG8EjtuZy+KH\nTWvRM+LYfQto3cF5DZL/J1PLPxisx/Z+AHG2U9aXojZwMpDjw81ciSrTCu+Xusie\nGaVzRXJaqCaxJo8uOqmNMGUW6Vtk377APbvzoFgoLFKv4GCDOxBaWD4n8Icc67RU\n7lZGYgfrZQgALyCvSxbYlNhSGgd33hF+YWawtSJDE7xsaBYz0WI4NhCuPWfFuphX\nz1ACRpW61zsTksC3PT6ozzOcic1QA2H98AThCcZpEwKBgQDuz6eaJnny3lE2ZIs+\nQR2MPL9YD828eMtQAJ9sh64AabfSwBAmfSRugWrcdOB8JPzNozM2rAW9rVCoAXsz\nmTkJlAy9xRDqeIZ/wxf0HwYa1NuvCZnzAIGZxDA8GrxnW9T9bEWnzzLs6WMD1WzQ\n0pfRXB9uOJW8UNZn1in6CjOkRwKBgQDMCk4L8SxsmsHA+mETeb7k2sHO2tjzhTOv\nEKD2Av8eRDIeHm+YRwhKblDbhaxMnqiyOzdlLFIRpi3nfxQo0qrdiTTcDsCEwNL6\nwfsRpTi0KWB+LJNDlvzgozigKn3S/btP9YmZNR1Hl5XvqhhP5i6L0zbVOqUj0uR0\nCZwxc8sbiwKBgCcu2SAYyg+IXKjhDFu1kWSOHxMS3L3cz/cbcwz6ohkdP3UL4FqA\nU/bxsxfi8WZNJ1GSQnfo97QseLxoKc/IhyxEJ2cHq4PdLKxP1WFPqc/DNxxcJe9S\nGPGi2As0k88dqS+/kRo8i+2FSaK6ZPVKaHCIffu2uxK/7L3yzMZi4CBHAoGAIsnn\nALZAIsxIGMUX5CAv4glCXiiGMQ8W/tRQ/WEJanmqKeR6lnYV/crNUoB6Hh43GRxr\nl351B7lTvlK2dzdkFp2cO6DwRjIyRrroOdv3zQ/4+cpT2YRW3V42+2gDSAQm+b0d\nltethFVeJRzVRFo0uXZrtPNo0LDWbspsrSnXCX0CgYBwJptu5XFo+cCcoOFxHBZk\neOCqHWKiUshAB7ygdIsFl0xzBks9WxUKcDxL0dHim2Lm1oCCg2xzYT2aHGLEPLdZ\nQOmU7O/w8xXdirF7JA1jXEWTS6+2QRmKArSdDQ5xQYzuRcPWDOuH4OxEJfYge5EP\niMtfv+9QXOUkUurDOGZq3w==\n-----END PRIVATE KEY-----\n"
FIREBASE_PROJECT_ID="flutter-himti-app-b2d87"

handlers:
  - url: /.*
    script: auto
