name: himti-api-dev

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GCP_REGISTRY: asia-southeast2-docker.pkg.dev
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_APP_NAME: ${{ secrets.APPLICATION }}

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Package if not exists
        run: |
          echo "Creating package if it doesn't exist"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages \
            -d '{"name":"${{ github.repository }}","visibility":"private"}'
        continue-on-error: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify image push
        run: |
          echo "Verifying image push"
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_PORT: ${{ secrets.DB_PORT }}
      REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD}}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME}}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Enable necessary APIs
        run: |
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable run.googleapis.com

      - name: Check if Artifact Registry repository exists
        id: check_repo
        run: |
          if gcloud artifacts repositories describe ${{ env.GCP_APP_NAME }} --location=asia-southeast2 &>/dev/null; then
            echo "Repository already exists"
            echo "repo_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Repository does not exist"
            echo "repo_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Artifact Registry repository
        if: steps.check_repo.outputs.repo_exists == 'false'
        run: |
          gcloud artifacts repositories create ${{ env.GCP_APP_NAME }} \
            --repository-format=docker \
            --location=asia-southeast2 \
            --description="Docker repository for ${{ env.GCP_APP_NAME }}"

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.GCP_REGISTRY }} --quiet

      - name: Pull image from GHCR
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Debug - List Artifact Registry repositories
        run: |
          echo "Listing Artifact Registry repositories"
          gcloud artifacts repositories list --location=asia-southeast2

      - name: Debug - Verify Docker configuration
        run: |
          echo "Verifying Docker configuration"
          docker info

      - name: Tag and push image to GCP
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_APP_NAME }}/${{ env.GCP_APP_NAME }}:${{ github.sha }}
          docker push ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_APP_NAME }}/${{ env.GCP_APP_NAME }}:${{ github.sha }}

      - name: Prepare environment variables
        run: |
          cat << EOF > env_vars.yaml
          DB_NAME: "${{ secrets.DB_NAME }}"
          DB_USERNAME: "${{ secrets.DB_USERNAME }}"
          DB_HOST: "${{ secrets.DB_HOST }}"
          DB_PASS: "${{ secrets.DB_PASS }}"
          DB_PORT: "${{ secrets.DB_PORT }}"
          REFRESH_TOKEN_SECRET_KEY: "${{ secrets.REFRESH_TOKEN_SECRET_KEY }}"
          ACCESS_TOKEN_SECRET_KEY: "${{ secrets.ACCESS_TOKEN_SECRET_KEY }}"
          MAIL_USERNAME: "${{ secrets.MAIL_USERNAME }}"
          MAIL_PASSWORD: "${{ secrets.MAIL_PASSWORD }}"
          BUCKET_NAME: "${{ secrets.BUCKET_NAME }}"
          EOF

      - name: Debug - Check env_vars.yaml content
        run: cat env_vars.yaml

      - name: Deploy Docker Image to Google Cloud Run
        run: |
          gcloud run deploy ${{ secrets.APPLICATION }} \
            --image ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_APP_NAME }}/${{ env.GCP_APP_NAME }}:${{ github.sha }} \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --env-vars-file env_vars.yaml \
            --verbosity=debug

      - name: Debug - Check deployment status
        if: failure()
        run: |
          gcloud run services describe ${{ secrets.APPLICATION }} \
            --region asia-southeast2 \
            --format='yaml(status)'

      - name: Debug - Check recent logs
        if: failure()
        run: |
          gcloud run services logs read --service=${{ secrets.APPLICATION }} \
            --region=asia-southeast2 \
            --limit=50